import clsx from 'clsx';
import { CircleAlert, Eye, Sparkles, TrendingUp, TrendingDown, ShieldCheck } from 'lucide-react';
import type { Analysis, Insight, InsightKind } from '../types';

const KIND_META: Record<
  InsightKind,
  { label: string; icon: typeof ShieldCheck; card: string; chip: string; iconColor: string }
> = {
  strength: {
    label: 'Strength',
    icon: ShieldCheck,
    card: 'border-emerald-200 bg-emerald-50/60',
    chip: 'bg-emerald-100 text-emerald-800',
    iconColor: 'text-emerald-600',
  },
  concern: {
    label: 'Concern',
    icon: CircleAlert,
    card: 'border-rose-200 bg-rose-50/60',
    chip: 'bg-rose-100 text-rose-800',
    iconColor: 'text-rose-600',
  },
  trend: {
    label: 'Trend',
    icon: TrendingUp,
    card: 'border-sky-200 bg-sky-50/60',
    chip: 'bg-sky-100 text-sky-800',
    iconColor: 'text-sky-600',
  },
  observation: {
    label: 'Observation',
    icon: Eye,
    card: 'border-ink-200 bg-ink-50/70',
    chip: 'bg-ink-200 text-ink-700',
    iconColor: 'text-ink-500',
  },
};

const SEVERITY_LABEL: Record<Insight['severity'], string> = {
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

function InsightCard({ insight }: { insight: Insight }) {
  const meta = KIND_META[insight.kind];
  // A downward trend deserves a downward arrow.
  const Icon =
    insight.kind === 'trend' && /fell|declined|contracted|reduced|down/i.test(insight.title)
      ? TrendingDown
      : meta.icon;

  return (
    <li className={clsx('rounded-lg border p-4', meta.card)}>
      <div className="flex items-start gap-3">
        <Icon className={clsx('mt-0.5 h-4 w-4 shrink-0', meta.iconColor)} aria-hidden />
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span className={clsx('rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide', meta.chip)}>
              {meta.label}
            </span>
            {insight.kind === 'concern' && (
              <span className="text-[10px] font-semibold uppercase tracking-wide text-ink-500">
                {SEVERITY_LABEL[insight.severity]} severity
              </span>
            )}
          </div>
          <h4 className="mt-1.5 text-sm font-semibold leading-snug text-ink-900">{insight.title}</h4>
          <p className="mt-1 text-sm leading-relaxed text-ink-700">{insight.detail}</p>
          {insight.evidence.length > 0 && (
            <ul className="mt-2.5 flex flex-wrap gap-1.5">
              {insight.evidence.map((item) => (
                <li
                  key={item}
                  className="rounded border border-ink-200 bg-white/70 px-1.5 py-0.5 font-mono text-[10px] text-ink-500"
                >
                  {item}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </li>
  );
}

const SECTION_ORDER: InsightKind[] = ['concern', 'strength', 'trend', 'observation'];

const SECTION_TITLES: Record<InsightKind, string> = {
  concern: 'Areas of concern',
  strength: 'Key strengths',
  trend: 'Changes since last year',
  observation: 'Other observations',
};

export function InsightsPanel({ analysis }: { analysis: Analysis }) {
  const sections = SECTION_ORDER.map((kind) => ({
    kind,
    items: analysis.insights.filter((insight) => insight.kind === kind),
  })).filter((section) => section.items.length > 0);

  return (
    <section className="animate-fade-up space-y-5">
      <div className="card card-pad bg-gradient-to-br from-teal-50 to-white">
        <div className="flex items-start justify-between gap-3">
          <h2 className="text-base font-semibold text-ink-900">Analysis</h2>
          <span
            className={clsx(
              'inline-flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold',
              analysis.narrativeFromLlm ? 'bg-violet-100 text-violet-800' : 'bg-ink-200 text-ink-700',
            )}
            title={
              analysis.narrativeFromLlm
                ? 'Written by Claude from the extracted figures. It was given the numbers and the ratios, never the document, and it did not recompute anything.'
                : 'Generated by the built-in rule engine. Every finding is derived from the figures in the table above.'
            }
          >
            {analysis.narrativeFromLlm ? (
              <>
                <Sparkles className="h-3 w-3" aria-hidden />
                Written by Claude
              </>
            ) : (
              'Rule-based analysis'
            )}
          </span>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-ink-800">{analysis.summary}</p>
      </div>

      {sections.map((section) => (
        <div key={section.kind}>
          <h3 className="label-caps mb-2.5">{SECTION_TITLES[section.kind]}</h3>
          <ul className="grid gap-3 lg:grid-cols-2">
            {section.items.map((insight) => (
              <InsightCard key={insight.id} insight={insight} />
            ))}
          </ul>
        </div>
      ))}

      {analysis.insights.length === 0 && (
        <p className="card card-pad text-sm text-ink-600">
          Not enough was extracted to draw conclusions from this document.
        </p>
      )}
    </section>
  );
}
